name: jpa shop Image Build
on:
  workflow_dispatch:
    inputs:
#      targetClient:
#        description: Target Client
#        required: true
      Message:
        description: Release Message (if Production)
        required: true
        default: description

permissions:
  contents: read

jobs:
  analyze-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Extract branch name
        id: extract-branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      branch: ${{ steps.extract-branch.outputs.branch }}

  setup-build-param:
    runs-on: ubuntu-latest
    needs: [analyze-tags]
    steps:
      - name: setup-build-param
        id: setup-build-param
        run: |
          echo ::set-output name=image::robi-t-backend
          echo ::set-output name=client::robi-ipcc-rpm-app

          if [ ${{ needs.analyze-tags.outputs.branch }} == production ]; then
              echo ::set-output name=image::robi-t-backend-prod
          elif [ ${{ needs.analyze-tags.outputs.branch }} == staging ]; then
              echo ::set-output name=image::robi-t-backend-staging
          else
              echo ::set-output name=image::robi-t-backend-dev
          fi
    outputs:
      image: ${{ steps.setup-build-param.outputs.image }}
      client: ${{ steps.setup-build-param.outputs.client }}

  build-image-backend:
    runs-on: ubuntu-latest
    needs: [analyze-tags, setup-build-param]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Get Short SHA in 8 Length
      - name: get shortsha
        id: vars
        run: echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})

      # Debug Version and Short SHA
      - name: Check output
        run: |
          echo ${{ needs.analyze-tags.outputs.previous-tag }}-${{ steps.vars.outputs.sha_short }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          USER_NAME: ${{ secrets.JIHONG_USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.JIHONG_SECRET_TOKEN }}
        run: ./gradlew build --exclude-task test :robi-ipcc-rpm-app:bootBuildImage --imageName=posicube/${{ needs.setup-build-param.outputs.image }}:${{ needs.analyze-tags.outputs.previous-tag }}-${{ steps.vars.outputs.sha_short }}

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish Docker image
        run: |
          docker tag posicube/${{ needs.setup-build-param.outputs.image }}:${{ needs.analyze-tags.outputs.previous-tag }}-${{ steps.vars.outputs.sha_short }} posicube/${{ needs.setup-build-param.outputs.image }}:latest
          docker push posicube/${{ needs.setup-build-param.outputs.image }}:${{ needs.analyze-tags.outputs.previous-tag }}-${{ steps.vars.outputs.sha_short }}
          docker push posicube/${{ needs.setup-build-param.outputs.image }}:latest
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
